name: Open Source NASA Code
author: Justin Gosses
title: Open Source NASA Codes
description: This site currently hasn't updated to NASA data, it is only updated naming.
remote_theme: LLNL/Jekyll-LLNL-Theme@main
shortname: NASA

# url: "https://softwareunderground.github.io/llnl.github.io/"
# repo_url: "https://github.com/softwareunderground/llnl.github.io"
baseurl: "/open_geosciene_code_projects_viz"

# LLNL Piwik Analytics https://analytics.llnl.gov
# piwik_id: 250

# Google Analytics ID
#google_analytics:
#  tracking_id: UA-75179431-1

# Twitter username (used by jekyll-seo-tag)
twitter:
  username: swung_org

# GitHub Metadata -- https://github.com/jekyll/github-metadata
repository: softwareunderground/open_geosciene_code_projects_viz
plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

kramdown:
  auto_ids: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/news/:year/:month/:day/:title/"

permalink: pretty

exclude:
    - CNAME
    - Gemfile
    - Gemfile.lock
    - README.md
    - Makefile
    - build
